monolog:
    handlers:
        main:
            type: group
            members: [file, graylog]
        file:
            type: rotating_file
            level: ERROR
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 10
        graylog:
            type: gelf
            # use INFO for Gelf as intercept extracts info level messages for display
            level: INFO
            publisher: "gelf.publisher"
