monolog:
    handlers:
        main:
            type: group
            members: [file, graylog]
        file:
            type: rotating_file
            level: ERROR
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        graylog:
            type: gelf
            level: ERROR
            publisher: "gelf.publisher"
