services:
    App\Client\BambooClient:
        public: true
    App\Client\GerritClient:
        public: true
    App\Client\GeneralClient:
        public: true
    App\Client\ForgeClient:
        public: true
    App\Service\LocalCoreGitService:
        public: true
