services:
    App\Client\BambooClient:
        tags:
            - testDouble
    App\Client\GerritClient:
        tags:
            - testDouble
    App\Client\GeneralClient:
        tags:
            - testDouble

