services:
    monolog.processor.add_field_processor:
        class: App\Monolog\Processor\AddFieldProcessor
        arguments:
            - { application: 'intercept', env: '%env(APP_ENV)%' }
        tags:
            - { name: monolog.processor, handler: 'graylog' }
