version: '3.6'
services:
  web:
    volumes:
      - type: tmpfs
        target: /var/www/html/var/cache
        tmpfs:
          size: 268435456
      - type: tmpfs
        target: /var/www/html/var/sessions
        tmpfs:
          size: 26843545
